name: admin_panel_dashboard
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter_svg: ^2.0.7
  fl_chart: ^0.63.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  lottie: ^2.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  assets:
      - assets/images/
      - assets/icons/
  fonts:
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis-Regular.ttf
  uses-material-design: true
